---
title: "My English activity log"
author:
  - name: Lisa Flasse
    url: {}
date: 11-12-2019
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

- Up to now :
  + phone and social media configured in english for some years
  + finished a few series and movies in english (with english subtitles)
  + watched a lot of videos on Youtube
  + read a few books, articles, and stories
- 28/11 : watched "The cabin in the woods" (En with EN subs)
- 29/11 : watched "The earthquake bird" (EN with EN subs)
- 01/12 : watched "Sinister" (EN with no subs)
- 13/12 : watched "Jigsaw" (EN with EN subs)
- 14/12 : watched "Pan's labyrinth" (EN with EN subs)
- 15/12 : watched a few episodes of "The big bang theory" (EN with EN subs)
- 19/12 : watched "Saw II" (EN with EN subs)
- 20/12 : watched "Don't f**k with cats" (EN with EN subs)
- 22/12 : watched "A cure for wellness" (EN with EN subs)
- 26/01 : watched "Saw VI" (EN with EN subs)
- 27/01 : watched "Saw VII" (EN with EN subs)
- 28/01 : watched three episodes of "The Witcher" (EN with EN subs)
- 31/01 : watched last episodes of "The Witcher" (EN with EN subs)
- 15/02 : read Lewis Carroll's "Alice's adventures in wonderland"
